name: Start AKS Cluster
description: Creates the AKS cluster and infrastructure

inputs:
  azure_credentials:
    description: The Azure credentials
    required: true
  run_id:
    description: Unique run identifier for resource naming
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Start AKS cluster
      id: start_aks
      shell: bash
      env:
        RUN_ID: ${{ inputs.run_id }}
      run: |
        bash uid2-shared-actions/scripts/aks/start_aks_cluster.sh
