name: Start AKS Private Operator
description: Spins up an AKS private operator

inputs:
  azure_credentials:
    description: The Azure credentials
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Start AKS private operator
      id: start_aks
      shell: bash
      run: |
        bash ${{ github.action_path }}/../../scripts/aks/start_aks_cluster.sh
