name: Prepare GCP Metadata
description: Prepares the GCP OIDC enclave metadata

inputs:
  operator_image_version:
    description: The uid2-operator image version
    default: latest
  target_environment:
    description: The target environment [mock, integ, prod]
    required: true
  gcp_service_account:
    description: The GCP service account
    required: true
  gcp_workload_identity_provider_id:
    description: The GCP workload identity provider id
    required: true
  gcp_registry:
    description: The GCP docker registry
    default: us-docker.pkg.dev

outputs:
  image_hash:
    description: The operator image hash
    value: ${{ steps.image_digest.outputs.image_hash }}
  operator_key:
    description: The operator key
    value: ${{ steps.operator_key.outputs.operator_key }}

runs:
  using: "composite"

  steps:
    - name: Authenticate with Google Cloud
      id: gcp_auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider_id }}
        service_account: ${{ inputs.gcp_service_account }}
        access_token_lifetime: 1200s

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Log in to the GCP Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.gcp_registry }}
        username: oauth2accesstoken
        password: ${{ steps.gcp_auth.outputs.access_token }}

    - name: Get image digest
      id: image_digest
      shell: bash
      run: |
        IMAGE_NAME="us-docker.pkg.dev/uid2-prod-project/iabtechlab/uid2-operator"
        IMAGE_TAG="${{ inputs.operator_image_version }}"

        # Pull the image to make sure it's available locally
        docker pull "${IMAGE_NAME}:${IMAGE_TAG}"

        # Get the digest
        IMAGE_HASH=$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_NAME}:${IMAGE_TAG}" | cut -d'@' -f2)
        echo "image_hash=${IMAGE_HASH}" >> $GITHUB_OUTPUT

    - name: Prepare GCP enclave ID
      id: enclave_id
      shell: bash
      env:
        IMAGE_HASH: ${{ steps.image_digest.outputs.image_hash }}
      run: |
        bash uid2-shared-actions/scripts/gcp/prepare_gcp_enclave_id.sh

    - name: Prepare GCP enclave metadata
      id: enclave_metadata
      if: ${{ inputs.target_environment == 'mock' }}
      shell: bash
      env:
        ENCLAVE_ID: ${{ steps.enclave_id.outputs.enclave_id }}
        ENCLAVE_PROTOCOL: gcp-oidc
      run: |
        bash uid2-shared-actions/scripts/save_enclave_id_to_admin.sh

    - name: Get operator key
      id: operator_key
      shell: bash
      env:
          IDENTITY_SCOPE: UID2
          TARGET_ENVIRONMENT: ${{ inputs.target_environment }}
          ENCLAVE_PROTOCOL: gcp-oidc
      run: |
        bash ./uid2-shared-actions/scripts/get_operator_key.sh
