name: Stop EKS Operator

inputs:
  eks_test_cluster:
    description: The EKS Test Cluster Name
    required: true
  eks_test_cluster_region:
    description: The EKS Test Cluster Region
    required: true

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.eks_test_cluster_region }}
        role-to-assume: arn:aws:iam::072245134533:role/github-runner-for-uid2-operator
    
    - name: Check AWS caller identity
      shell: bash
      run: aws sts get-caller-identity

    - name: Set up kubernetes context
      shell: bash
      run: |
        aws eks --region ${{ inputs.eks_test_cluster_region }} update-kubeconfig --name ${{ inputs.eks_test_cluster }}

    - name: Stop EKS operator
      id: stop_eks
      shell: bash
      run: |
        kubectl delete namespace compute --ignore-not-found=true
        kubectl delete service operator-service --ignore-not-found=true
        kubectl delete deployment operator --ignore-not-found=true
        kubectl delete secret github-test-secret --ignore-not-found=true
