name: Stop EKS Operator

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::072245134533:role/github-runner-for-uid2-operator
    
    - name: Check AWS caller identity
      shell: bash
      run: aws sts get-caller-identity

    - name: Set up kubernetes context
      shell: bash
      run: |
        aws eks --region us-east-2 update-kubeconfig --name uid-test-git-us-east-2

    - name: Stop EKS operator
      id: stop_eks
      shell: bash
      run: |
        kubectl delete deployment uid2-operator
        kubectl delete secret github-test-secret
