name: Stop EKS Operator
description: Stops up an EKS private operator

inputs:
  eks_test_cluster:
    description: The EKS test cluster name
    required: true
  eks_test_cluster_region:
    description: The EKS test cluster region
    required: true
  identity_scope:
    description: The identity scope [UID2, EUID]
    required: true

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.eks_test_cluster_region }}
        role-to-assume: arn:aws:iam::072245134533:role/github-runner-for-uid2-operator
    
    - name: Check AWS caller identity
      shell: bash
      run: aws sts get-caller-identity

    - name: Set up kubernetes context
      shell: bash
      run: |
        aws eks --region ${{ inputs.eks_test_cluster_region }} update-kubeconfig --name ${{ inputs.eks_test_cluster }}

    - name: Stop EKS operator
      id: stop_eks
      shell: bash
      env:
        IDENTITY_SCOPE: ${{ inputs.identity_scope }}
      run: |
        bash uid2-shared-actions/scripts/eks/stop_eks_enclave.sh
