name: Start Azure Private Operator
description: Spins up an Azure private operator

inputs:
  bore_url_core:
    description: The bore URL for core service
    required: true
  bore_url_optout:
    description: The bore URL for optout service
    required: true
  template_file:
    description: The template file
    required: true
  parameters_file:
    description: The parameters file
    required: true
  azure_credentials:
    description: The Azure credentials
    required: true

outputs:
  azure_container_group_name:
    description: The Azure instance name
    value: ${{ steps.start_azure.outputs.azure_container_group_name }}
  uid2_e2e_pipeline_operator_url:
    description: The Azure operator URL
    value: ${{ steps.start_azure.outputs.uid2_e2e_pipeline_operator_url }}

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Start Azure private operator
      id: start_azure
      shell: bash
      env:
        BORE_URL_CORE: ${{ inputs.bore_url_core }}
        BORE_URL_OPTOUT: ${{ inputs.bore_url_optout }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
        PARAMETERS_FILE: ${{ inputs.parameters_file }}
      run: |
        bash uid2-shared-actions/scripts/azure/start_azure_enclave.sh
