name: Stop Azure Private Operator
description: Spins down an Azure private operator

inputs:
  azure_credentials:
    description: The Azure credentials
    required: true
  azure_container_group_name:
    description: The Azure instance name
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Stop Azure private operator
      shell: bash
      env:
        AZURE_CONTAINER_GROUP_NAME: ${{ inputs.azure_container_group_name }}
      run: |
        bash uid2-shared-actions/scripts/azure/stop_azure_enclave.sh
