name: Create releases
description: Create releases and build changelogs

inputs:
  is_release:
    description: True if a release should be created
    default: false
  version_number_input:
    description: If set, the version number will not be incremented and the given number will be used.
    default: ''
  tags:
    description: The docker image tags
    default: ''
  image_tag:
    description: The image tag for the new version
    default: ''
  github_token:
    description: The github token to login to Docker container
    required: true

runs:
  using: "composite" 

  steps:
    - name: Build Changelog
      id: github_release
      if: ${{ inputs.is_release == 'true' }}
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        toTag: v${{ inputs.version_number_input }}
        configurationJson: |
          {
            "template": "#{{CHANGELOG}}\n## Installation\n```\ndocker pull ${{ inputs.tags }}\n```\n\n## Image reference to deploy: \n```\n${{ inputs.image_tag }}\n```\n\n## Changelog\n#{{UNCATEGORIZED}}",
            "pr_template": " - #{{TITLE}} - ( PR: ##{{NUMBER}} )"
          }
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Create Release
      if: ${{ inputs.is_release == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ inputs.version_number_input }}
        body: ${{ steps.github_release.outputs.changelog }}
        draft: true
