name: Download_gpg_key
description: 'Downloads the gpg key into the settings.xml file'
inputs:
  key:
    description: 'The Key to be imported'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v21
      with: 
        repositories: >
          []  
        servers: >
          [
            {
              "id": ${repo.id},
              "username": ${repo.login}
            }
          ]      
    - name: Import GPG key 
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        echo -n "$GPG_SIGNING_KEY" | base64 --decode > private.key 
        gpg --batch --import private.key
      env:
        GPG_SIGNING_KEY: ${{ inputs.key }}
