name: Prepare AKS Metadata
description: Prepares the AKS CC artifacts and enclave metadata

inputs:
  operator_image_version:
    description: The uid2-operator image version
    default: latest
  target_environment:
    description: The target environment [mock, integ, prod]
    required: true
  bore_url_core:
    description: The bore URL for core service
    required: true
  bore_url_optout:
    description: The bore URL for optout service
    required: true
  operator_key:
    description: The operator key secret for the target environment
    required: true
  run_id:
    description: Unique run identifier to avoid Azure resource conflicts
    required: true
outputs:
  template_file:
    description: The template file
    value: ${{ steps.enclave_artifacts.outputs.template_file }}

runs:
  using: "composite"

  steps:
    - name: check azure-cli version
      shell: bash
      run: |
        az --version

    - name: Generate AKS enclave deployment artifacts
      id: enclave_artifacts
      shell: bash
      env:
        BORE_URL_CORE: ${{ inputs.bore_url_core }}
        BORE_URL_OPTOUT: ${{ inputs.bore_url_optout }}
        IMAGE_VERSION: ${{ inputs.operator_image_version }}
        TARGET_ENVIRONMENT: ${{ inputs.target_environment }}
        OPERATOR_KEY: ${{ inputs.operator_key }}
        RUN_ID: ${{ inputs.run_id }}
      run: |
        bash uid2-shared-actions/scripts/aks/prepare_aks_artifacts.sh

    - name: Prepare AKS enclave ID
      id: enclave_id
      shell: bash
      env:
        POLICY_DIGEST_FILE: ${{ steps.enclave_artifacts.outputs.policy_digest_file }}
      run: |
        bash uid2-shared-actions/scripts/aks/prepare_aks_enclave_id.sh

    - name: Prepare AKS enclave metadata
      id: enclave_metadata
      shell: bash
      env:
        ENCLAVE_ID: ${{ steps.enclave_id.outputs.enclave_id }}
        ENCLAVE_PROTOCOL: azure-cc
      run: |
        bash uid2-shared-actions/scripts/save_enclave_id_to_admin.sh
