name: Stop AKS Private Operator
description: Spins down an AKS private operator

inputs:
  azure_credentials:
    description: The Azure credentials
    required: true
  run_id:
    description: Unique run identifier for resource naming
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Stop AKS private operator
      shell: bash
      env:
        RUN_ID: ${{ inputs.run_id }}
      run: |
        bash ${{ github.action_path }}/../../scripts/aks/stop_aks_enclave.sh
