name: Stop AKS Private Operator
description: Spins down an AKS private operator

inputs:
  azure_credentials:
    description: The Azure credentials
    required: true

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Stop AKS private operator
      shell: bash
      run: |
        bash uid2-shared-actions/scripts/aks/stop_aks_enclave.sh
