name: Start GCP Private Operator
description: Spins up a GCP private operator

inputs:
  bore_url_core:
    description: The bore URL for core service
    required: true
  bore_url_optout:
    description: The bore URL for optout service
    required: true
  gcp_project:
    description: The name of the GCP project
    required: true
  gcp_service_account:
    description: The GCP service account
    required: true
  image_hash:
    description: The operator image hash of the operator image version
    required: true
  operator_key:
    description: The operator key
    required: true

outputs:
  gcp_instance_name:
    description: The GCP instance name
    value: ${{ steps.start_gcp.outputs.GCP_INSTANCE_NAME }}
  uid2_pipeline_e2e_operator_url:
    description: The GCP operator URL
    value: ${{ steps.start_gcp.outputs.uid2_pipeline_e2e_operator_url }}

runs:
  using: "composite"

  steps:
    - name: Start GCP private operator
      id: start_gcp
      shell: bash
      env:
        #To Do: revert it back after testing done. Intentionally trigger failure
        BORE_URL_CORE: http://192.0.2.1
        BORE_URL_OPTOUT: http://192.0.2.1
#        BORE_URL_CORE: ${{ inputs.bore_url_core }}
#        BORE_URL_OPTOUT: ${{ inputs.bore_url_optout }}
        GCP_PROJECT: ${{ inputs.gcp_project }}
        SERVICE_ACCOUNT: ${{ inputs.gcp_service_account }}
        OPERATOR_KEY: ${{ inputs.operator_key }}
        IMAGE_HASH: ${{ inputs.image_hash }}
      run: |
        bash uid2-shared-actions/scripts/gcp/start_gcp_enclave.sh
