name: Start AKS Private Operator
description: Spins up an AKS private operator

inputs:
  template_file:
    description: The template file
    required: true
  azure_credentials:
    description: The Azure credentials
    required: true
  run_id:
    description: Unique run identifier for resource naming
    required: true

outputs:
  uid2_pipeline_e2e_operator_url:
    description: The AKS operator URL
    value: ${{ steps.start_aks.outputs.uid2_pipeline_e2e_operator_url }}

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Start AKS private operator
      id: start_aks
      shell: bash
      env:
        TEMPLATE_FILE: ${{ inputs.template_file }}
        RUN_ID: ${{ inputs.run_id }}
      run: |
        bash ${{ github.action_path }}/../../scripts/aks/start_aks_enclave.sh
