name: Start AKS Private Operator
description: Spins up an AKS private operator

inputs:
  bore_url_core:
    description: The bore URL for core service
    required: true
  bore_url_optout:
    description: The bore URL for optout service
    required: true
  output_template_file:
    description: The output template file
    required: true
  azure_credentials:
    description: The Azure credentials
    required: true
  aks_operator_key:
    description: The AKS operator key
    required: true

outputs:
  aks_container_group_name:
    description: The AKS instance name
    value: ${{ steps.start_aks.outputs.AZURE_CONTAINER_GROUP_NAME }}
  uid2_e2e_pipeline_operator_url:
    description: The AKS operator URL
    value: ${{ steps.start_aks.outputs.uid2_e2e_pipeline_operator_url }}

runs:
  using: "composite"

  steps:
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}
        enable-AzPSSession: true

    - name: Start AKS private operator
      id: start_aks
      shell: bash
      env:
        BORE_URL_CORE: ${{ inputs.bore_url_core }}
        BORE_URL_OPTOUT: ${{ inputs.bore_url_optout }}
        OUTPUT_TEMPLATE_FILE: ${{ inputs.output_template_file }}
        AKS_OPERATOR_KEY: ${{ inputs.aks_operator_key }}
      run: |
        bash uid2-shared-actions/scripts/aks/start_aks_enclave.sh
