name: Prepare AWS Metadata
description: Prepares the AWS Nitro enclave metadata

inputs:
  operator_image_version:
    description: The version of UID2 operator image
    default: latest
  admin_root:
    description: The root path for uid2-admin folder
    default: ../uid2-admin

outputs:
  operator_key:
    description: The operator key
    value: ${{ steps.metadata.outputs.OPERATOR_KEY }}
  image_hash:
    description: The operator image version
    value: ${{ steps.get_digest.outputs.IMAGE_HASH }}

runs:
  using: "composite"
  steps:
    - name: Authenticate with Google Cloud
      id: gcp_auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider_id }}
        service_account: ${{ inputs.gcp_service_account }}
        access_token_lifetime: 1200s

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Log in to the Docker container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Image Digest
      id: get_digest
      shell: bash
      run: |
        IMAGE_NAME="us-docker.pkg.dev/uid2-prod-project/iabtechlab/uid2-operator"
        IMAGE_TAG="${{ inputs.operator_image_version }}"

        # Pull the image to make sure it's available locally
        docker pull "${IMAGE_NAME}:${IMAGE_TAG}"

        # Get the digest
        IMAGE_HASH=$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_NAME}:${IMAGE_TAG}" | cut -d'@' -f2)
        echo "::set-output name=image_hash::${IMAGE_HASH}"
