name: Vulnerability Scanning
description: Scans for vulnerabilities
inputs:
  scan_severity:
    description: The severity that will cause the action to report if a vulnerability at that level is detected. UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    default: CRITICAL,HIGH
  failure_severity:
    description: The severity that will cause the action to fail if a vulnerability at that level is detected. UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    default: CRITICAL,HIGH
  publish_vulnerabilities:
    description: If true, will attempt to publish the results to the GitHub security tab
    default: 'true'
  image_ref: 
    description: The image reference to scan vulnerability on. If set it will be a image scan.
    default: ''
  scan_type:
    description: The scan-type for aquasecurity/trivy-action action. Default to a fs scan.
    default: fs
  full_report:
    description: Whether to scan and report for MEDIUM,HIGH,CRITICAL
    default: 'false'
  skip_files:
    description: Comma separated list of files to skip during scanning
    default: ''
runs:
  using: "composite"
  steps:
  - name: Checkout repo
    uses: actions/checkout@v4
    with:
      repository: IABTechLab/uid2-shared-actions
      ref: v2
      path: tmp-vulnerability-scan

  - name: Retrieve trivy-secret.yaml
    shell: bash
    run: |
      cp tmp-vulnerability-scan/trivy-secret.yaml ./trivy-secret.yaml
      rm -rf tmp-vulnerability-scan

  - name: Setup oras
    uses: oras-project/setup-oras@v1

  - name: Get current date
    id: date
    shell: bash
    run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  - name: Check Cache for Databases
    id: cache-check
    uses: actions/cache@v4
    with:
      path: ${{ github.workspace }}/.cache/trivy
      key: cache-trivy-${{ steps.date.outputs.date }}

  - name: Download and extract the vulnerability DB
    if: ${{ !steps.cache-check.outputs.cache-hit }}
    shell: bash
    run: |
      mkdir -p $GITHUB_WORKSPACE/.cache/trivy/db
      oras pull ghcr.io/aquasecurity/trivy-db:2
      tar -xzf db.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/db
      rm db.tar.gz

  - name: Download and extract the Java DB
    if: ${{ !steps.cache-check.outputs.cache-hit }}
    shell: bash
    run: |
      mkdir -p $GITHUB_WORKSPACE/.cache/trivy/java-db
      oras pull ghcr.io/aquasecurity/trivy-java-db:1
      tar -xzf javadb.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/java-db
      rm javadb.tar.gz

  - name: Cache DBs
    uses: actions/cache/save@v4
    if: ${{ !steps.cache-check.outputs.cache-hit }}
    with:
      path: ${{ github.workspace }}/.cache/trivy
      key: cache-trivy-${{ steps.date.outputs.date }}

  - name: Generate Trivy vulnerability scan report
    uses: aquasecurity/trivy-action@0.26.0
    if: inputs.publish_vulnerabilities == 'true'
    with:
      image-ref: ${{ inputs.image_ref }}
      scan-type: ${{ inputs.scan_type }}
      skip-files: ${{ inputs.skip_files }}
      format: 'sarif'
      exit-code: '0'
      ignore-unfixed: false
      severity: ${{ inputs.scan_severity }}
      output: 'trivy-results.sarif'
      hide-progress: true
    env:
      TRIVY_SKIP_DB_UPDATE: true
      TRIVY_SKIP_JAVA_DB_UPDATE: true

  - name: Upload Trivy scan report to GitHub Security tab
    uses: github/codeql-action/upload-sarif@v3
    if: inputs.publish_vulnerabilities == 'true'
    with:
      sarif_file: 'trivy-results.sarif'

  - name: Local vulnerability scanner for MEDIUM,HIGH,CRITICAL for reporting
    if: ${{ inputs.full_report  == 'true' }}
    uses: aquasecurity/trivy-action@0.26.0
    with:
      image-ref: ${{ inputs.image_ref }}
      scan-type: ${{ inputs.scan_type }}
      skip-files: ${{ inputs.skip_files }}
      format: 'table'
      exit-code: '0'
      ignore-unfixed: false
      severity: 'MEDIUM,HIGH,CRITICAL'
      hide-progress: true
    env:
      TRIVY_SKIP_DB_UPDATE: true
      TRIVY_SKIP_JAVA_DB_UPDATE: true

  - name: Test with Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.14.0
    with:
      image-ref: ${{ inputs.image_ref }}
      scan-type: ${{ inputs.scan_type }}
      skip-files: ${{ inputs.skip_files }}
      format: 'table'
      exit-code: '1'
      ignore-unfixed: false
      severity: ${{ inputs.failure_severity }}
      hide-progress: true
    env:
      TRIVY_SKIP_DB_UPDATE: true
      TRIVY_SKIP_JAVA_DB_UPDATE: true
