name: Prepare AWS Metadata
description: Prepares the AWS Nitro enclave metadata

inputs:
  operator_image_version:
    description: The uid2-operator image version
    default: latest
  admin_root:
    description: The root path for uid2-admin folder
    default: uid2-admin
  aws_pcr0:
    description: The AWS PCR0
    required: true

outputs:
  operator_key:
    description: The operator key
    value: ${{ steps.enclave_metadata.outputs.OPERATOR_KEY }}

runs:
  using: "composite"

  steps:
    - name: Prepare EKS enclave metadata
      id: enclave_metadata
      shell: bash
      env:
        ADMIN_ROOT: ${{ inputs.admin_root }}
        ENCLAVE_ID: ${{ inputs.aws_pcr0 }}
        ENCLAVE_PROTOCOL: aws-nitro
      run: |
        bash uid2-shared-actions/scripts/save_enclave_id_to_admin.sh
