name: Prepare EKS Metadata
description: Prepares the EKS Nitro enclave metadata

inputs:
  operator_image_version:
    description: The uid2-operator image version
    default: latest
  eks_pcr0:
    description: The EKS PCR0
    required: true

outputs:
  operator_key:
    description: The operator key
    value: ${{ steps.enclave_metadata.outputs.OPERATOR_KEY }}

runs:
  using: "composite"

  steps:
    - name: Prepare EKS enclave metadata
      id: enclave_metadata
      shell: bash
      env:
        ENCLAVE_ID: ${{ inputs.eks_pcr0 }}
        ENCLAVE_PROTOCOL: aws-nitro
      run: |
        bash uid2-shared-actions/scripts/save_enclave_id_to_admin.sh
