name: Delete draft releases
description: Delete any draft releases

inputs:
  github_token:
    description: The GITHUB_TOKEN to use for the target repo
    required: false
  repo_owner:
    description: The owner of the target repo
    required: true
  repo_name:
    description: The name of the target repo
    required: true

runs:
  using: "composite" 

  steps:
    - name: Delete draft releases
      uses: actions/github-script@v7
      id: delete-release
      with:
        result-encoding: string
        script: |
          let allReleases = (await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          })).data;

          console.log("Total release count: " + allReleases.length);

          let draftReleases = allReleases.filter((release) => {
            return release.draft == true && !release.body.includes('--editing--');
          });

          console.log("Draft count: " + draftReleases.length);

          draftReleases.forEach((release) => {
            console.log("Deleting draft release: " + release.id)
            /*await github.rest.repos.deleteRelease({
              owner: '${{ inputs.repo_owner }}',
              repo: '${{ inputs.repo_name }}',
              release_id: release.id
            })*/
          });



