name: Delete draft releases
description: Delete any draft releases

inputs:
  github_token:
    description: The GITHUB_TOKEN to use for the target repo
    required: false
  repo_owner:
    description: The owner of the target repo
    required: true
  repo_name:
    description: The name of the target repo
    required: true

runs:
  using: "composite" 

  steps:
    - name: Delete draft releases
      uses: actions/github-script@v7
      id: delete-release
      with:
        github-token: ${{ inputs.github_token }}
        result-encoding: string
        script: |
          console.log(context);

          let allReleases = await github.rest.repos.listReleases({
            owner: '${{ inputs.repo_owner }}',
            repo: '${{ inputs.repo_name }}'
          });

          console.log("Releases found: " + allReleases.length);

          let draftReleases = allReleases.data.filter((release) => {
            return release.draft == true && !release.body.contains("--editing--")
          });

          draftReleases.forEach((release) => {
            console.log("Deleting draft release: " + release.id)
            //await github.rest.repos.deleteRelease({
            //  owner: '${{ inputs.repo_owner }}',
            //  repo: '${{ inputs.repo_name }}',
            //  release_id: release.id
            //})
          });



