global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'instance']
  group_wait: 45s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'blackhole'

receivers:
- name: blackhole
