name: Start EKS Private Operator
description: Spins up an EKS private operator

inputs:
  bore_url_core:
    description: The bore URL for core service
    required: true
  bore_url_optout:
    description: The bore URL for optout service
    required: true
  bore_url_localstack:
    description: The bore URL for localstack service
    required: true
  identity_scope:
    description: The identity scope [UID2, EUID]
    required: true
  operator_image_version:
    description: The uid2-operator image version
    default: latest
  operator_root:
    description: The root path for uid2-operator folder
    default: uid2-operator
  operator_key:
    description: The operator key
    required: true
  eks_test_cluster:
    description: The EKS Test Cluster Name
    required: true
  eks_test_cluster_region:
    description: The EKS Test Cluster Region
    required: true
  


# outputs:
#   uid2_e2e_pipeline_operator_url:
#     description: The EKS operator URL
#     value: ${{ steps.start_aws.outputs.uid2_e2e_pipeline_operator_url }}

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.eks_test_cluster_region }}
        role-to-assume: arn:aws:iam::072245134533:role/github-runner-for-uid2-operator
    
    - name: Check AWS caller identity
      shell: bash
      run: aws sts get-caller-identity

    - name: Set up kubernetes context
      shell: bash
      run: |
        aws eks --region ${{ inputs.eks_test_cluster_region }} update-kubeconfig --name ${{ inputs.eks_test_cluster }}

    - name: Create secrets in the kubernetes cluster
      id: create_secrets
      shell: bash
      env:
        OPERATOR_KEY: ${{ inputs.operator_key }}
        BORE_URL_CORE: ${{ inputs.bore_url_core }}
        BORE_URL_OPTOUT: ${{ inputs.bore_url_optout }}
      run: |
        bash uid2-shared-actions/scripts/eks/create_secret_in_k8.sh

    - name: Prepare EKS enclave deployment files
      id: enclave_metadata
      shell: bash
      env:
        IMAGE_VERSION: ${{ inputs.operator_image_version }}
        OPERATOR_ROOT: ${{ inputs.operator_root }}
      run: |
        bash uid2-shared-actions/scripts/eks/prepare_eks_deployment_files.sh

    - name: Start EKS operator
      id: start_eks
      shell: bash
      run: |
        cat ${{ inputs.operator_root }}/scripts/aws/eks/deployment_files/test-deployment.yaml
        kubectl apply -f ${{ inputs.operator_root }}/scripts/aws/eks/deployment_files/test-deployment.yaml
        kubectl get pods --all-namespace
