name: Prepare Azure Metadata
description: Prepares the Azure CC artifacts and enclave metadata

inputs:
  operator_image_version:
    description: The uid2-operator image version
    default: latest
outputs:
  template_file:
    description: The template file
    value: ${{ steps.enclave_artifacts.outputs.template_file }}
  parameters_file:
    description: The parameters file
    value: ${{ steps.enclave_artifacts.outputs.parameters_file }}

runs:
  using: "composite"

  steps:
    - name: check azure-cli version
      shell: bash
      run: |
        az --version
    
    - name: Generate Azure enclave deployment artifacts
      id: enclave_artifacts
      shell: bash
      env:
        IMAGE_VERSION: ${{ inputs.operator_image_version }}
      run: |
        bash uid2-shared-actions/scripts/azure/prepare_azure_artifacts.sh

    - name: Prepare Azure enclave ID
      id: enclave_id
      shell: bash
      env:
        POLICY_DIGEST_FILE: ${{ steps.enclave_artifacts.outputs.policy_digest_file }}
      run: |
        bash uid2-shared-actions/scripts/azure/prepare_azure_enclave_id.sh

    - name: Prepare Azure enclave metadata
      id: enclave_metadata
      if: ${{ inputs.target_environment == 'mock' }}
      shell: bash
      env:
        ENCLAVE_ID: ${{ steps.enclave_id.outputs.enclave_id }}
        ENCLAVE_PROTOCOL: azure-cc
      run: |
        bash uid2-shared-actions/scripts/save_enclave_id_to_admin.sh
