name: Vulnerability Scan Failure Notification
on:
  workflow_call:
    inputs:
      vulnerability_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised. Must be one of ['CRITICAL', 'CRITICAL,HIGH' or 'CRITICAL,HIGH,MEDIUM'] (without space in between).
        type: string
        default: 'CRITICAL,HIGH'
      publish_vulnerabilities:
        description: If true, will attempt to publish the results to the GitHub security tab
        required: false
        default: 'true'
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: false

jobs:
  check_dependency:
    runs-on:  ubuntu-latest #${{ inputs.platform }}

    steps:
      - name: Vulnerability Scan
        id: vulnerability-scan
        uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan_filesystem@v3
        with:
          scan_severity: HIGH,CRITICAL
          failure_severity: ${{ inputs.vulnerability_severity }}
          publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
        continue-on-error: true

      - name: Check for vulnerability scan failure
        if: ${{ steps.vulnerability-scan == 'failure' }}
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'test description2 + ${{ toJSON(steps.vulnerability-scan)}}'
          SLACK_TITLE: Test title 2
          SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        uses: rtCamp/action-slack-notify@v2

      - name: fail the workflow if vulnerability scan fails
        if: ${{ steps.vulnerability-scan.outcome == 'failure' }}
        shell: bash
        run: |
          echo "Failing the workflow due to vulnerability scan failure"
          exit 1

