name: Shared Pipeline to build and publish images to Docker
on:
  workflow_call:
    inputs:
      release_type:
        description: The type of version number to return. Must be one of [Snapshot, Patch, Minor or Major]
        required: true
        type: string
      publish_vulnerabilities:
        description: If true, will attempt to publish any vulnerabilities to GitHub. Defaults to true. Set to false for private repos.
        type: string
        default: true
      version_number_input:
        description: The version number to publish for the docker repo
        type: string
        default: ''
      force_release:
        description: If 'yes', will force the creation a release, if 'no' will not create a release. 'branch' will use release_type and the branch to determine if a release should be created.
        type: string
        default: 'branch'
      docker_file:
        description: The Dockerfile used to build and publish Docker image
        type: string
        default: ''
    # outputs:
    #   version_number_output:
    #     description: The complete version number 
    #     value: ${{ jobs.buildImage.outputs.jar_version }}
    #   image_tag:
    #     description: The tag used to describe the image in docker
    #     value: ${{ jobs.buildImage.outputs.image_tag }}
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  buildImage:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      packages: write
      pull-requests: write
    outputs:
      jar_version: ${{ inputs.version_number_input }}
      image_tag: ${{ steps.updatePom.outputs.image_tag }}
    steps:
      - name: Setup
        id: setup
        uses: IABTechLab/uid2-shared-actions/actions/shared_publish_setup@kcc-UID2-2674-implement-shared-publish-to-docker-versioned
        with:
          release_type: ${{ inputs.release_type }}

      - name: Publish to Docker
        id: publishToDocker
        uses: IABTechLab/uid2-shared-actions/actions/shared_publish_to_docker@kcc-UID2-2674-implement-shared-publish-to-docker-versioned
        with:
          image_tag: ${{ inputs.version_number_input }}
          not_snapshot: ${{ steps.setup.outputs.not_snapshot }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_file: ${{ inputs.docker_file }}

      - name: Create Release
        id: github_release
        uses: IABTechLab/uid2-shared-actions/actions/shared_create_releases@kcc-UID2-2674-implement-shared-publish-to-docker-versioned
        with:
          is_release: ${{ steps.setup.outputs.is_release }}
          version_number_input: ${{ inputs.version_number_input }}
          tags: ${{ steps.publishToDocker.outputs.tags }}
          image_tag: ${{ inputs.version_number_input }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
