name: Vulnerability Scan Failure Notification
on:
  workflow_call:
    inputs:
      vulnerability_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised. Must be one of ['CRITICAL', 'CRITICAL,HIGH' or 'CRITICAL,HIGH,MEDIUM'] (without space in between).
        type: string
        default: 'CRITICAL,HIGH'
      publish_vulnerabilities:
        description: If true, will attempt to publish the results to the GitHub security tab.
        default: 'true'
        type: string
      platform:
        description: The OS runner to execute the vulnerability scan (e.g., ubuntu-latest, macos-latest, windows-latest).
        default: 'ubuntu-latest'
        type: string

jobs:
  vulnerability_scan:
    runs-on:  ${{ inputs.platform }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout uid2-shared-actions repo
        uses: actions/checkout@v4
        with:
          ref: v3
          repository: IABTechLab/uid2-shared-actions
          path: uid2-shared-actions

      - name: Vulnerability Scan
        id: vulnerability-scan
        uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan_filesystem@v3
        with:
          scan_severity: HIGH,CRITICAL
          failure_severity: ${{ inputs.vulnerability_severity }}
          publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
        continue-on-error: true

      - name: Check for vulnerability scan failure
        if: ${{ steps.vulnerability-scan.outcome == 'failure' }}
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'The vulnerability scan has encountered a failure.'
          SLACK_TITLE: Vulnerability Scan Failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2

      - name: fail the workflow if vulnerability scan fails
        if: ${{ steps.vulnerability-scan.outcome == 'failure' }}
        shell: bash
        run: |
          echo "Failing the workflow due to vulnerability scan failure"
          exit 1

