name: Shared Check Stable Dependencies
on:
  workflow_call:

jobs:
  check_dependency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Resolve dependencies
        run: mvn -B dependency:resolve

      - name: List and check for snapshot
        run: |
          export SNAPSHOT_COUNT=$(mvn -o dependency:list | grep -e "SNAPSHOT:" | wc -l)
          if [ $SNAPSHOT_COUNT -gt 0 ]
          then
            exit 1
          fi
