name: Shared Increase Version Number
on:
  workflow_call:
    inputs:
      release_type:
        description: The type of version number to return. Must be one of [Snapshot, Patch, Minor or Major]
        required: true
        type: string
      version_number_input:
        description: If set, the version number will not be incremented and the given number will be used.
        default: ''
        type: string
      working_dir:
        description: The path to the directory for which the version should be determined.
        type: string
        default: '.'
    outputs:
      new_version:
        description: The new version number to publish for the docker repo
        value: ${{ jobs.incrementVersionNumber.outputs.new_version }}
      image_tag:
        description: The image tag used to extract metadata for Docker
        value: ${{ jobs.incrementVersionNumber.outputs.image_tag }}
      git_tag_or_hash:
        description: The git tag or hash (for snapshots) containing the updated version.
        value: ${{ jobs.incrementVersionNumber.git_tag_or_hash }}

jobs:
  incrementVersionNumber:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      image_tag: ${{ steps.updatePackageJson.outputs.image_tag }}
      git_tag_or_hash: ${{ steps.commit-and-tag.result == 'success' && steps.commit-and-tag.outputs.git_tag_or_hash || steps.commit-without-tag.outputs.git_tag_or_hash }}
    steps:
      - name: Setup
        id: setup
        uses: IABTechLab/uid2-shared-actions/actions/shared_publish_setup@v2
        with:
          release_type: ${{ inputs.release_type }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set version number
        id: version
        uses: IABTechLab/uid2-shared-actions/actions/version_number@v2
        with:
          type: ${{ inputs.release_type }}
          version_number: ${{ inputs.version_number_input }}
          branch_name: ${{ github.ref }}
          working_dir: ${{ inputs.working_dir }}

      - name: Update ${{ inputs.working_dir }}/package.json
        id: updatePackageJson
        run: |
          current_version=$(jq -r '.version')
          new_version=${{ steps.version.outputs.new_version }}
          jq --arg v "$new_version" ".version = \$v" "${{ inputs.working_dir }}/package.json" > tmp.json && mv tmp.json "${{ inputs.working_dir }}/package.json"
          echo "Version number updated from $current_version to $new_version"
          echo "image_tag=${{ steps.version.outputs.new_version }}" >> $GITHUB_OUTPUT

      - name: Update ${{ inputs.working_dir }}/package-lock.json
        id: updatePackageLockJson
        run: |
          npm install --package-lock-only

      - name: Commit ${{ inputs.working_dir }}/package.json, ${{ inputs.working_dir }}/package-lock.json and ${{ inputs.working_dir }}/version.json
        if: ${{ inputs.version_number_input == '' && steps.setup.outputs.IS_RELEASE != 'true' }} 
        id: commit-without-tag
        uses: IABTechLab/uid2-shared-actions/actions/commit_pr_and_merge@main
        with:
          add: '${{ inputs.working_dir }}/package.json ${{ inputs.working_dir }}/package-lock.json ${{ inputs.working_dir }}/version.json'
          message: 'Released ${{ inputs.release_type }} version: ${{ steps.version.outputs.new_version }}'

      - name: Commit ${{ inputs.working_dir }}/package.json, ${{ inputs.working_dir }}/package-lock.json, ${{ inputs.working_dir }}/version.json and set tag
        if: ${{ inputs.version_number_input == '' && steps.setup.outputs.IS_RELEASE == 'true' }} 
        id: commit-and-tag
        uses: IABTechLab/uid2-shared-actions/actions/commit_pr_and_merge@main
        with:
          add: '${{ inputs.working_dir }}/package.json ${{ inputs.working_dir }}/package-lock.json ${{ inputs.working_dir }}/version.json'
          message: 'Released ${{ inputs.release_type }} version: ${{ steps.version.outputs.new_version }}'
          tag: v${{ steps.version.outputs.new_version }}
