name: Shared Pre-Commit
on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: trivyfs-docker --all-files