name: Run operator E2E tests
on:
  workflow_call:
    inputs:
      core_root:
        description: 'The root path for uid2-core folder'
        type: string
        default: '../uid2-core'
      optout_root:
        description: 'The root path for uid2-optout folder'
        type: string
        default: '../uid2-optout'
      admin_root:
        description: 'The root path for uid2-admin folder'
        type: string
        default: '../uid2-admin'
      operator_root:
        description: 'The root path for uid2-operator folder'
        type: string
        default: '../uid2-operator'
      operator_image_version:
        description: 'The version of UID2 operator image'
        type: string
        default: 'latest'
      core_image_version:
        description: 'The version of UID2 core image'
        type: string
        default: 'latest'
      optout_image_version:
        description: 'The version of UID2 optout image'
        type: string
        default: 'latest'
      e2e_image_version:
        description: 'The version of E2E image'
        type: string
        default: 'latest'
      core_branch:
        description: 'The branch of UID2-core to test on'
        type: string
        default: 'main'
      optout_branch:
        description: 'The branch of UID2-optout to test on'
        type: string
        default: 'main'
      admin_branch:
        description: 'The branch of UID2-admin to test on'
        type: string
        default: 'main'
      operator_branch:
        description: 'The branch of UID2-operator to test on'
        type: string
        default: 'main'
      operator_type:
        description: 'The type of operator [either public or gcp or azure]'
        type: string
        default: 'public'
      gcp_project:
        description: 'The name of the GCP project'
        type: string
        required: true
      gcp_service_account:
        description: 'The GCP service account'
        type: string
        required: true
      gcp_workload_identity_provider_id:
        description: 'The GCP workload identity provider id'
        type: string
        required: true
      uid2_e2e_identity_scope:
        description: 'Environment variable to run the E2E test'
        required: false
        type: string
        default: 'UID2'
      uid2_e2e_pipeline_operator_type:
        description: 'Environment variable to run the E2E test'
        required: false
        type: string
        default: 'PUBLIC'
      uid2_e2e_pipeline_operator_url:
        description: 'Environment variable to run the E2E test'
        required: false
        type: string
        default: 'http://publicoperator:8080'
      uid2_e2e_pipeline_operator_cloud_provider:
        description: 'Environment variable to run the E2E test'
        required: false
        type: string
        default: 'PUBLIC'
      uid2_e2e_phone_support:
        description: 'Environment variable to run the E2E test'
        required: false
        type: string
        default: 'true'

env:
  REGISTRY: ghcr.io

jobs:
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      id-token: write
    steps:
      - name: Log in to the Docker container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Checkout full history
        uses: actions/checkout@v3

      - name: Checkout uid2-core repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.core_branch }}
          repository: IABTechLab/uid2-core
          path: uid2-core

      - name: Checkout uid2-optout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.optout_branch }}
          repository: IABTechLab/uid2-optout
          path: uid2-optout

      - name: Checkout uid2-admin repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.admin_branch }}
          repository: IABTechLab/uid2-admin
          path: uid2-admin

      - name: Checkout uid2-operator repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.operator_branch }}
          repository: IABTechLab/uid2-operator
          path: uid2-operator

      - name: Checkout uid2-shared-actions repo
        uses: actions/checkout@v3
        with:
          ref: kcc-UID2-2339-create-test-pipeline-for-gcp
          repository: IABTechLab/uid2-shared-actions
          path: uid2-shared-actions

      - name: Checkout uid2-e2e repo
        uses: actions/checkout@v3
        with:
          repository: IABTechLab/uid2-e2e
          path: uid2-e2e

      - name: Bring up bore
        id: bore
        if: ${{ inputs.operator_type == 'gcp' || inputs.operator_type == 'azure' }}
        run: |
          cd e2e && bash ../uid2-shared-actions/scripts/setup_bore.sh

      - name: Bring up docker compose
        id: docker-compose
        env:
          CORE_ROOT: ${{ inputs.core_root }}
          OPTOUT_ROOT: ${{ inputs.optout_root }}
          ADMIN_ROOT: ${{ inputs.admin_root }}
          OPERATOR_ROOT: ${{ inputs.operator_root }}
          CORE_VERSION: ${{ inputs.core_image_version }}
          OPTOUT_VERSION: ${{ inputs.optout_image_version }}
          OPERATOR_VERSION: ${{ inputs.operator_image_version }}
          E2E_VERSION: ${{ inputs.e2e_image_version }}
          OPERATOR_TYPE: ${{ inputs.operator_type }}
          BORE_URL_CORE: ${{ steps.bore.outputs.BORE_URL_CORE }}
          BORE_URL_OPTOUT: ${{ steps.bore.outputs.BORE_URL_OPTOUT }}
          BORE_URL_LOCALSTACK: ${{ steps.bore.outputs.BORE_URL_LOCALSTACK }}
        run: |
          cd e2e && bash ../uid2-shared-actions/scripts/prepare-resources-for-e2e-docker-compose.sh

      - name: Start GCP private operator
        id: start_gcp_private_operator
        if: ${{ inputs.operator_type == 'gcp'}}
        uses: IABTechLab/uid2-shared-actions/actions/start_gcp_private_operator@kcc-UID2-2339-create-test-pipeline-for-gcp
        with:
          operator_image_version: ${{ inputs.operator_image_version }}
          admin_root: ${{ inputs.admin_root }}
          bore_url_core: ${{ steps.bore.outputs.BORE_URL_CORE }}
          bore_url_optout: ${{ steps.bore.outputs.BORE_URL_OPTOUT }}
          bore_url_localstack: ${{ steps.bore.outputs.BORE_URL_LOCALSTACK }}
          gcp_workload_identity_provider_id: ${{ inputs.gcp_workload_identity_provider_id }}
          gcp_service_account: ${{ inputs.gcp_service_account }}
          gcp_project: ${{ inputs.gcp_project }}

      - name: Run e2e tests
        id: e2e
        uses: IABTechLab/uid2-shared-actions/actions/run_e2e_tests@v2
        with:
          e2e_image_version: ${{ inputs.e2e_image_version }}
