name: Shared Maven Build And Test
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: '11'
      vulnerability_scan_only:
        description: If true, only the vulnerability scanning step will run.
        type: string
        default: 'false'
      publish_vulnerabilities:
        type: string
        default: 'true'
      vulnerability_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised. Must be one of ['CRITICAL', 'CRITICAL,HIGH' or 'CRITICAL,HIGH,MEDIUM'] (without space in between).
        type: string
        default: 'CRITICAL,HIGH'
      working_dir:
        description: The path to the pom.xml file.
        type: string
        default: '.'
    secrets:
      slack_webhook:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Checkout uid2-shared-actions repo
        uses: actions/checkout@v4
        with:
          ref: v3
          repository: IABTechLab/uid2-shared-actions
          path: uid2-shared-actions

      - name: Set up JDK
        if: ${{ inputs.vulnerability_scan_only == 'false' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Generate code coverage
        if: ${{ inputs.vulnerability_scan_only == 'false' }}
        run: mvn jacoco:report
        working-directory: ${{ inputs.working_dir }}

      - name: Archive code coverage results
        if: ${{ inputs.vulnerability_scan_only == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ${{ inputs.working_dir }}/target/site/jacoco/*

      - name: Vulnerability Scan
        uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan_filesystem@ccm-UID2-4528-report-faillures-on-scheduled-vulnerability-detection-runs
        with:
          scan_severity: HIGH,CRITICAL
          failure_severity: ${{ inputs.vulnerability_severity }}
          publish_vulnerabilities: ${{ inputs.publish_vulnerabilities }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
