name: Test shared-build-and-test
on:
  push:
    branches:
      - bmz-fix-vulnerability-scan-checkout-path
  workflow_dispatch:

jobs:
  test-default-working-dir:
    uses: ./.github/workflows/shared-build-and-test.yaml
    with:
      publish_vulnerabilities: 'false'
      working_dir: 'test-maven-project'
