name: Increment version and update via PR
on: 
  workflow_call:
    inputs:
      tag:
        description: 'Tag'
        required: false
        type: string
        default: ''
      add:
        description: 'Add files'
        type: string
        required: false
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Bump version file
        shell: bash
        run: |
          awk '{$1=$1+1;print}' version.txt > version.tmp
          cp version.tmp version.txt
          cp version.tmp version-extra.txt
          rm version.tmp

      - name: Commit-PR-merge
        uses: IABTechLab/uid2-shared-actions/actions/commit_pr_and_merge@llp-uid2-2236-auto-pr-action
        with:
          message: 'Update the version file'
          tag: ${{ inputs.tag }}
          add: ${{ inputs.add }}